### ISSUE TITLE
AWS and domain

### ISSUE THREAD

**Issue by cuibaps1** [Just-Web/Player-Connect-App#10]
As a software developer, I want to set up the server for the project, so I can run it.

**Comment by raomidi** [comment]
I have purchased the domain: playerconnect.net

**Comment by sonamnahar21** [comment]
I have created AWS account. Please Check Slack for credentials. 
To setup EC2 service it's giving me an error (see attached screenshot.) 
I will try to setup EC2 tomorrow. 
<img width="1245" alt="screen shot 2018-10-14 at 7 47 53 pm" src="https://user-images.githubusercontent.com/18060167/46927458-621a7c80-cfea-11e8-99a1-8626f39e3fd8.png">
